### ISSUE TITLE
[Question] How did you publish your features in VSCODE ?

### ISSUE THREAD

**Issue by guiyomh** [eitsupi/devcontainer-features#28]
Bonjour,

I found your features via vscode.
<img width="619" alt="Screenshot 2022-11-03 at 16 38 58" src="https://user-images.githubusercontent.com/363162/199768852-dfa398ac-6829-4e10-90e0-0192346582bc.png">

I would also like to publish my features, but I did not find how to do it. Can you explain me how you did it?
Today I have to add them by hand, I can't find them via the GUI.

**Comment by eitsupi** [comment]
See https://containers.dev/implementors/features-distribution/

**Comment by guiyomh** [comment]
oh thank, I havent see this documentation.

**Comment by eitsupi** [comment]
@guiyomh Hi, I check your repo https://github.com/guiyomh/features.

1. Why don't you take your fish down since the original script author, @andreiborisov, and I have one that we maintain in the following repo.
  https://github.com/meaningful-ooo/devcontainer-features
2. About just, I did not know yours. If you need it, please transplant mine to your repo (mine looks more complete).

I do not think it is a good idea to have two identical Features.

**Comment by andreiborisov** [comment]
I agree that double effort for such a niche thing as a fish feature doesn't make sense.

@guiyomh you’re welcome to contribute to https://github.com/meaningful-ooo/devcontainer-features

**Comment by guiyomh** [comment]
@eitsupi no worries, I didn't know your repo. And I did mine a few months ago. Indeed having 2 times the same feature is not very judicious. I will make an MR on your repo to add alpine support for fish.

**Comment by guiyomh** [comment]
@eitsupi @andreiborisov Do you know how to indicate in my repo that my feature is deprecated in favor of yours?

**Comment by guiyomh** [comment]
@eitsupi I am ok with your proposition about just

**Comment by eitsupi** [comment]
@guiyomh Glad to hear that! I will create PRs in your repository later and then update this repository to take down the just Feature in this repo.
